// Code generated by protoc-gen-go. DO NOT EDIT.
// source: subs/subspb/subspb.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubInitialCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubInitialCheckRequest) Reset()         { *m = SubInitialCheckRequest{} }
func (m *SubInitialCheckRequest) String() string { return proto.CompactTextString(m) }
func (*SubInitialCheckRequest) ProtoMessage()    {}
func (*SubInitialCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb912f61f4810e9f, []int{0}
}

func (m *SubInitialCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubInitialCheckRequest.Unmarshal(m, b)
}
func (m *SubInitialCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubInitialCheckRequest.Marshal(b, m, deterministic)
}
func (m *SubInitialCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubInitialCheckRequest.Merge(m, src)
}
func (m *SubInitialCheckRequest) XXX_Size() int {
	return xxx_messageInfo_SubInitialCheckRequest.Size(m)
}
func (m *SubInitialCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubInitialCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubInitialCheckRequest proto.InternalMessageInfo

type SubInitialCheckResponse struct {
	IsSet                bool     `protobuf:"varint,1,opt,name=isSet,proto3" json:"isSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubInitialCheckResponse) Reset()         { *m = SubInitialCheckResponse{} }
func (m *SubInitialCheckResponse) String() string { return proto.CompactTextString(m) }
func (*SubInitialCheckResponse) ProtoMessage()    {}
func (*SubInitialCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb912f61f4810e9f, []int{1}
}

func (m *SubInitialCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubInitialCheckResponse.Unmarshal(m, b)
}
func (m *SubInitialCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubInitialCheckResponse.Marshal(b, m, deterministic)
}
func (m *SubInitialCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubInitialCheckResponse.Merge(m, src)
}
func (m *SubInitialCheckResponse) XXX_Size() int {
	return xxx_messageInfo_SubInitialCheckResponse.Size(m)
}
func (m *SubInitialCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubInitialCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubInitialCheckResponse proto.InternalMessageInfo

func (m *SubInitialCheckResponse) GetIsSet() bool {
	if m != nil {
		return m.IsSet
	}
	return false
}

type SubSetRequest struct {
	AnchorPositionX      float32  `protobuf:"fixed32,1,opt,name=anchorPositionX,proto3" json:"anchorPositionX,omitempty"`
	AnchorPositionY      float32  `protobuf:"fixed32,2,opt,name=anchorPositionY,proto3" json:"anchorPositionY,omitempty"`
	AnchorPositionZ      float32  `protobuf:"fixed32,3,opt,name=anchorPositionZ,proto3" json:"anchorPositionZ,omitempty"`
	AnchorRotationW      float32  `protobuf:"fixed32,4,opt,name=anchorRotationW,proto3" json:"anchorRotationW,omitempty"`
	AnchorRotationX      float32  `protobuf:"fixed32,5,opt,name=anchorRotationX,proto3" json:"anchorRotationX,omitempty"`
	AnchorRotationY      float32  `protobuf:"fixed32,6,opt,name=anchorRotationY,proto3" json:"anchorRotationY,omitempty"`
	AnchorRotationZ      float32  `protobuf:"fixed32,7,opt,name=anchorRotationZ,proto3" json:"anchorRotationZ,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSetRequest) Reset()         { *m = SubSetRequest{} }
func (m *SubSetRequest) String() string { return proto.CompactTextString(m) }
func (*SubSetRequest) ProtoMessage()    {}
func (*SubSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb912f61f4810e9f, []int{2}
}

func (m *SubSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSetRequest.Unmarshal(m, b)
}
func (m *SubSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSetRequest.Marshal(b, m, deterministic)
}
func (m *SubSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSetRequest.Merge(m, src)
}
func (m *SubSetRequest) XXX_Size() int {
	return xxx_messageInfo_SubSetRequest.Size(m)
}
func (m *SubSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubSetRequest proto.InternalMessageInfo

func (m *SubSetRequest) GetAnchorPositionX() float32 {
	if m != nil {
		return m.AnchorPositionX
	}
	return 0
}

func (m *SubSetRequest) GetAnchorPositionY() float32 {
	if m != nil {
		return m.AnchorPositionY
	}
	return 0
}

func (m *SubSetRequest) GetAnchorPositionZ() float32 {
	if m != nil {
		return m.AnchorPositionZ
	}
	return 0
}

func (m *SubSetRequest) GetAnchorRotationW() float32 {
	if m != nil {
		return m.AnchorRotationW
	}
	return 0
}

func (m *SubSetRequest) GetAnchorRotationX() float32 {
	if m != nil {
		return m.AnchorRotationX
	}
	return 0
}

func (m *SubSetRequest) GetAnchorRotationY() float32 {
	if m != nil {
		return m.AnchorRotationY
	}
	return 0
}

func (m *SubSetRequest) GetAnchorRotationZ() float32 {
	if m != nil {
		return m.AnchorRotationZ
	}
	return 0
}

type SubSetResponse struct {
	IsSet                bool     `protobuf:"varint,1,opt,name=isSet,proto3" json:"isSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSetResponse) Reset()         { *m = SubSetResponse{} }
func (m *SubSetResponse) String() string { return proto.CompactTextString(m) }
func (*SubSetResponse) ProtoMessage()    {}
func (*SubSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb912f61f4810e9f, []int{3}
}

func (m *SubSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSetResponse.Unmarshal(m, b)
}
func (m *SubSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSetResponse.Marshal(b, m, deterministic)
}
func (m *SubSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSetResponse.Merge(m, src)
}
func (m *SubSetResponse) XXX_Size() int {
	return xxx_messageInfo_SubSetResponse.Size(m)
}
func (m *SubSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubSetResponse proto.InternalMessageInfo

func (m *SubSetResponse) GetIsSet() bool {
	if m != nil {
		return m.IsSet
	}
	return false
}

type SubGetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubGetRequest) Reset()         { *m = SubGetRequest{} }
func (m *SubGetRequest) String() string { return proto.CompactTextString(m) }
func (*SubGetRequest) ProtoMessage()    {}
func (*SubGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb912f61f4810e9f, []int{4}
}

func (m *SubGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubGetRequest.Unmarshal(m, b)
}
func (m *SubGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubGetRequest.Marshal(b, m, deterministic)
}
func (m *SubGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubGetRequest.Merge(m, src)
}
func (m *SubGetRequest) XXX_Size() int {
	return xxx_messageInfo_SubGetRequest.Size(m)
}
func (m *SubGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubGetRequest proto.InternalMessageInfo

type SubGetResponse struct {
	AnchorPositionX      float32  `protobuf:"fixed32,1,opt,name=anchorPositionX,proto3" json:"anchorPositionX,omitempty"`
	AnchorPositionY      float32  `protobuf:"fixed32,2,opt,name=anchorPositionY,proto3" json:"anchorPositionY,omitempty"`
	AnchorPositionZ      float32  `protobuf:"fixed32,3,opt,name=anchorPositionZ,proto3" json:"anchorPositionZ,omitempty"`
	AnchorRotationW      float32  `protobuf:"fixed32,4,opt,name=anchorRotationW,proto3" json:"anchorRotationW,omitempty"`
	AnchorRotationX      float32  `protobuf:"fixed32,5,opt,name=anchorRotationX,proto3" json:"anchorRotationX,omitempty"`
	AnchorRotationY      float32  `protobuf:"fixed32,6,opt,name=anchorRotationY,proto3" json:"anchorRotationY,omitempty"`
	AnchorRotationZ      float32  `protobuf:"fixed32,7,opt,name=anchorRotationZ,proto3" json:"anchorRotationZ,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubGetResponse) Reset()         { *m = SubGetResponse{} }
func (m *SubGetResponse) String() string { return proto.CompactTextString(m) }
func (*SubGetResponse) ProtoMessage()    {}
func (*SubGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb912f61f4810e9f, []int{5}
}

func (m *SubGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubGetResponse.Unmarshal(m, b)
}
func (m *SubGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubGetResponse.Marshal(b, m, deterministic)
}
func (m *SubGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubGetResponse.Merge(m, src)
}
func (m *SubGetResponse) XXX_Size() int {
	return xxx_messageInfo_SubGetResponse.Size(m)
}
func (m *SubGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubGetResponse proto.InternalMessageInfo

func (m *SubGetResponse) GetAnchorPositionX() float32 {
	if m != nil {
		return m.AnchorPositionX
	}
	return 0
}

func (m *SubGetResponse) GetAnchorPositionY() float32 {
	if m != nil {
		return m.AnchorPositionY
	}
	return 0
}

func (m *SubGetResponse) GetAnchorPositionZ() float32 {
	if m != nil {
		return m.AnchorPositionZ
	}
	return 0
}

func (m *SubGetResponse) GetAnchorRotationW() float32 {
	if m != nil {
		return m.AnchorRotationW
	}
	return 0
}

func (m *SubGetResponse) GetAnchorRotationX() float32 {
	if m != nil {
		return m.AnchorRotationX
	}
	return 0
}

func (m *SubGetResponse) GetAnchorRotationY() float32 {
	if m != nil {
		return m.AnchorRotationY
	}
	return 0
}

func (m *SubGetResponse) GetAnchorRotationZ() float32 {
	if m != nil {
		return m.AnchorRotationZ
	}
	return 0
}

type SubManyTimesRequest struct {
	IpAddr               string   `protobuf:"bytes,1,opt,name=ipAddr,proto3" json:"ipAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubManyTimesRequest) Reset()         { *m = SubManyTimesRequest{} }
func (m *SubManyTimesRequest) String() string { return proto.CompactTextString(m) }
func (*SubManyTimesRequest) ProtoMessage()    {}
func (*SubManyTimesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb912f61f4810e9f, []int{6}
}

func (m *SubManyTimesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubManyTimesRequest.Unmarshal(m, b)
}
func (m *SubManyTimesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubManyTimesRequest.Marshal(b, m, deterministic)
}
func (m *SubManyTimesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubManyTimesRequest.Merge(m, src)
}
func (m *SubManyTimesRequest) XXX_Size() int {
	return xxx_messageInfo_SubManyTimesRequest.Size(m)
}
func (m *SubManyTimesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubManyTimesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubManyTimesRequest proto.InternalMessageInfo

func (m *SubManyTimesRequest) GetIpAddr() string {
	if m != nil {
		return m.IpAddr
	}
	return ""
}

type SubManyTimesResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubManyTimesResponse) Reset()         { *m = SubManyTimesResponse{} }
func (m *SubManyTimesResponse) String() string { return proto.CompactTextString(m) }
func (*SubManyTimesResponse) ProtoMessage()    {}
func (*SubManyTimesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb912f61f4810e9f, []int{7}
}

func (m *SubManyTimesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubManyTimesResponse.Unmarshal(m, b)
}
func (m *SubManyTimesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubManyTimesResponse.Marshal(b, m, deterministic)
}
func (m *SubManyTimesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubManyTimesResponse.Merge(m, src)
}
func (m *SubManyTimesResponse) XXX_Size() int {
	return xxx_messageInfo_SubManyTimesResponse.Size(m)
}
func (m *SubManyTimesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubManyTimesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubManyTimesResponse proto.InternalMessageInfo

func (m *SubManyTimesResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*SubInitialCheckRequest)(nil), "subs.SubInitialCheckRequest")
	proto.RegisterType((*SubInitialCheckResponse)(nil), "subs.SubInitialCheckResponse")
	proto.RegisterType((*SubSetRequest)(nil), "subs.SubSetRequest")
	proto.RegisterType((*SubSetResponse)(nil), "subs.SubSetResponse")
	proto.RegisterType((*SubGetRequest)(nil), "subs.SubGetRequest")
	proto.RegisterType((*SubGetResponse)(nil), "subs.SubGetResponse")
	proto.RegisterType((*SubManyTimesRequest)(nil), "subs.SubManyTimesRequest")
	proto.RegisterType((*SubManyTimesResponse)(nil), "subs.SubManyTimesResponse")
}

func init() { proto.RegisterFile("subs/subspb/subspb.proto", fileDescriptor_fb912f61f4810e9f) }

var fileDescriptor_fb912f61f4810e9f = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x94, 0xcb, 0x4a, 0xc3, 0x40,
	0x14, 0x86, 0x6d, 0x6c, 0x63, 0x3d, 0x5e, 0x0a, 0xd3, 0x52, 0xc7, 0xa0, 0x20, 0x59, 0x48, 0x37,
	0xa6, 0x62, 0x9f, 0x40, 0x5d, 0x94, 0x2e, 0x14, 0xc9, 0x08, 0x36, 0xd9, 0x25, 0xed, 0x40, 0x07,
	0x6b, 0x12, 0x33, 0x33, 0x82, 0xaf, 0xe1, 0xbb, 0xe8, 0xf3, 0x49, 0x2e, 0x4d, 0x93, 0x66, 0x14,
	0x1f, 0xc0, 0x4d, 0xc2, 0x39, 0xe7, 0xfb, 0x73, 0xf9, 0xf9, 0xcf, 0x00, 0xe6, 0xd2, 0xe7, 0xc3,
	0xe4, 0x12, 0xf9, 0xf9, 0xcd, 0x8a, 0xe2, 0x50, 0x84, 0xa8, 0x99, 0x54, 0x26, 0x86, 0x3e, 0x91,
	0xfe, 0x24, 0x60, 0x82, 0x79, 0xcb, 0xdb, 0x05, 0x9d, 0x3d, 0xdb, 0xf4, 0x55, 0x52, 0x2e, 0xcc,
	0x21, 0x1c, 0xd5, 0x26, 0x3c, 0x0a, 0x03, 0x4e, 0x51, 0x0f, 0x5a, 0x8c, 0x13, 0x2a, 0x70, 0xe3,
	0xac, 0x31, 0x68, 0xdb, 0x59, 0x61, 0x7e, 0x6a, 0x70, 0x40, 0xa4, 0x4f, 0xa8, 0xc8, 0x1f, 0x81,
	0x06, 0xd0, 0xf1, 0x82, 0xd9, 0x22, 0x8c, 0x1f, 0x42, 0xce, 0x04, 0x0b, 0x83, 0x69, 0xaa, 0xd0,
	0xec, 0xcd, 0x76, 0x9d, 0x74, 0xb0, 0xa6, 0x22, 0x9d, 0x3a, 0xe9, 0xe2, 0x6d, 0x15, 0xe9, 0xae,
	0x49, 0x3b, 0x14, 0x5e, 0xd2, 0x7a, 0xc2, 0xcd, 0x32, 0x59, 0xb4, 0xeb, 0xe4, 0x14, 0xb7, 0x54,
	0xe4, 0xb4, 0x4e, 0x3a, 0x58, 0x57, 0x91, 0x4e, 0x9d, 0x74, 0xf1, 0x8e, 0x8a, 0x74, 0xcd, 0x73,
	0x38, 0x5c, 0xd9, 0xf6, 0xab, 0xbf, 0x9d, 0xd4, 0xde, 0x71, 0x61, 0xaf, 0xf9, 0xa5, 0xa5, 0xca,
	0x71, 0x49, 0xf9, 0xef, 0xf8, 0x5f, 0x1c, 0xbf, 0x80, 0x2e, 0x91, 0xfe, 0x9d, 0x17, 0xbc, 0x3f,
	0xb2, 0x17, 0xca, 0x57, 0x71, 0xed, 0x83, 0xce, 0xa2, 0xeb, 0xf9, 0x3c, 0x4e, 0x3d, 0xdb, 0xb5,
	0xf3, 0xca, 0xb4, 0xa0, 0x57, 0xc5, 0x73, 0xb3, 0xfb, 0xa0, 0xc7, 0x94, 0xcb, 0xa5, 0x58, 0xf1,
	0x59, 0x75, 0xf5, 0xa1, 0xc1, 0x1e, 0x91, 0x3e, 0x27, 0x34, 0x7e, 0x63, 0x33, 0x8a, 0x26, 0xb0,
	0x5f, 0xd6, 0xa3, 0x63, 0x2b, 0x59, 0x3d, 0x4b, 0xf1, 0x09, 0x86, 0xa1, 0x1a, 0x65, 0xaf, 0x33,
	0xb7, 0x2e, 0x1b, 0xe8, 0x1e, 0x3a, 0x1b, 0x4b, 0x89, 0x4e, 0x0a, 0x89, 0x62, 0x8b, 0x8d, 0xd3,
	0x1f, 0xa6, 0xf9, 0x2f, 0x8c, 0x40, 0xcf, 0x12, 0x84, 0xba, 0x05, 0xb8, 0x4e, 0x98, 0xd1, 0xab,
	0x36, 0x2b, 0x22, 0x52, 0x11, 0x11, 0x95, 0xa8, 0x94, 0xe9, 0x9b, 0xb6, 0xab, 0x67, 0xc7, 0x8f,
	0xaf, 0xa7, 0xe7, 0xcf, 0xe8, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xd3, 0xd5, 0x5e, 0x9b, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SubsServiceClient is the client API for SubsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubsServiceClient interface {
	SubManyTimes(ctx context.Context, in *SubManyTimesRequest, opts ...grpc.CallOption) (SubsService_SubManyTimesClient, error)
	SubInitialCheck(ctx context.Context, in *SubInitialCheckRequest, opts ...grpc.CallOption) (*SubInitialCheckResponse, error)
	SubGet(ctx context.Context, in *SubGetRequest, opts ...grpc.CallOption) (*SubGetResponse, error)
	SubSet(ctx context.Context, in *SubSetRequest, opts ...grpc.CallOption) (*SubSetResponse, error)
}

type subsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubsServiceClient(cc grpc.ClientConnInterface) SubsServiceClient {
	return &subsServiceClient{cc}
}

func (c *subsServiceClient) SubManyTimes(ctx context.Context, in *SubManyTimesRequest, opts ...grpc.CallOption) (SubsService_SubManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SubsService_serviceDesc.Streams[0], "/subs.SubsService/SubManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &subsServiceSubManyTimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubsService_SubManyTimesClient interface {
	Recv() (*SubManyTimesResponse, error)
	grpc.ClientStream
}

type subsServiceSubManyTimesClient struct {
	grpc.ClientStream
}

func (x *subsServiceSubManyTimesClient) Recv() (*SubManyTimesResponse, error) {
	m := new(SubManyTimesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *subsServiceClient) SubInitialCheck(ctx context.Context, in *SubInitialCheckRequest, opts ...grpc.CallOption) (*SubInitialCheckResponse, error) {
	out := new(SubInitialCheckResponse)
	err := c.cc.Invoke(ctx, "/subs.SubsService/SubInitialCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subsServiceClient) SubGet(ctx context.Context, in *SubGetRequest, opts ...grpc.CallOption) (*SubGetResponse, error) {
	out := new(SubGetResponse)
	err := c.cc.Invoke(ctx, "/subs.SubsService/SubGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subsServiceClient) SubSet(ctx context.Context, in *SubSetRequest, opts ...grpc.CallOption) (*SubSetResponse, error) {
	out := new(SubSetResponse)
	err := c.cc.Invoke(ctx, "/subs.SubsService/SubSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubsServiceServer is the server API for SubsService service.
type SubsServiceServer interface {
	SubManyTimes(*SubManyTimesRequest, SubsService_SubManyTimesServer) error
	SubInitialCheck(context.Context, *SubInitialCheckRequest) (*SubInitialCheckResponse, error)
	SubGet(context.Context, *SubGetRequest) (*SubGetResponse, error)
	SubSet(context.Context, *SubSetRequest) (*SubSetResponse, error)
}

// UnimplementedSubsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSubsServiceServer struct {
}

func (*UnimplementedSubsServiceServer) SubManyTimes(req *SubManyTimesRequest, srv SubsService_SubManyTimesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubManyTimes not implemented")
}
func (*UnimplementedSubsServiceServer) SubInitialCheck(ctx context.Context, req *SubInitialCheckRequest) (*SubInitialCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubInitialCheck not implemented")
}
func (*UnimplementedSubsServiceServer) SubGet(ctx context.Context, req *SubGetRequest) (*SubGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubGet not implemented")
}
func (*UnimplementedSubsServiceServer) SubSet(ctx context.Context, req *SubSetRequest) (*SubSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubSet not implemented")
}

func RegisterSubsServiceServer(s *grpc.Server, srv SubsServiceServer) {
	s.RegisterService(&_SubsService_serviceDesc, srv)
}

func _SubsService_SubManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubManyTimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubsServiceServer).SubManyTimes(m, &subsServiceSubManyTimesServer{stream})
}

type SubsService_SubManyTimesServer interface {
	Send(*SubManyTimesResponse) error
	grpc.ServerStream
}

type subsServiceSubManyTimesServer struct {
	grpc.ServerStream
}

func (x *subsServiceSubManyTimesServer) Send(m *SubManyTimesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SubsService_SubInitialCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubInitialCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubsServiceServer).SubInitialCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subs.SubsService/SubInitialCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubsServiceServer).SubInitialCheck(ctx, req.(*SubInitialCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubsService_SubGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubsServiceServer).SubGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subs.SubsService/SubGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubsServiceServer).SubGet(ctx, req.(*SubGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubsService_SubSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubsServiceServer).SubSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subs.SubsService/SubSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubsServiceServer).SubSet(ctx, req.(*SubSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SubsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "subs.SubsService",
	HandlerType: (*SubsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubInitialCheck",
			Handler:    _SubsService_SubInitialCheck_Handler,
		},
		{
			MethodName: "SubGet",
			Handler:    _SubsService_SubGet_Handler,
		},
		{
			MethodName: "SubSet",
			Handler:    _SubsService_SubSet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubManyTimes",
			Handler:       _SubsService_SubManyTimes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "subs/subspb/subspb.proto",
}
